#!/usr/bin/env python3
"""Hand-authored ZIP fixture corpus for S4 Y3 (G5, bounded ZIP expansion).

Every fixture here is built directly with Python's standard-library
`zipfile` module — never generated by `sergeant-rs`'s own extractor, which
does not exist as of this file's authorship (mirrors
`tests/fixtures/anydoc_corpus/build_docx_fixtures.py`'s own discipline:
`MANIFEST.md`'s expected counts were written by reading this script's own
output byte-for-byte, before `tests/y3_zip_adapter.rs` ever ran against it).

Run from this directory: `python3 build_zip_fixtures.py`.
"""

import os
import zipfile

OUT = os.path.join(os.path.dirname(__file__), "zip_fixtures")
os.makedirs(OUT, exist_ok=True)


def build_01_plain_and_directory():
    """Two ordinary files under one directory entry, plus one top-level
    file. Every entry is admitted; the directory entry is its own
    `Coverage::Discovered` row, not a child."""
    path = os.path.join(OUT, "01-plain-and-directory.zip")
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("readme.txt", b"top-level readme\n")
        z.writestr("notes/", b"")  # explicit directory entry
        z.writestr("notes/a.md", b"# A\n\nbody\n")
        z.writestr("notes/b.txt", b"plain text body\n")


def build_02_symlink():
    """One ordinary file, one symlink entry pointing outside the archive
    root. The symlink must be refused; the ordinary file must be admitted."""
    path = os.path.join(OUT, "02-symlink.zip")
    with zipfile.ZipFile(path, "w", zipfile.ZIP_STORED) as z:
        z.writestr("safe.txt", b"ordinary content\n")
        link = zipfile.ZipInfo("escape-link")
        # Unix mode in the top 16 bits of external_attr: S_IFLNK (0o120000)
        # | rwxrwxrwx (0o777) — the exact shape zip2's own `unix_mode()`
        # reads (VERIFIED against the crate's own `src/types.rs`, this
        # wave's research: `S_IFLNK = 0o0_120_000`).
        link.external_attr = (0o120777) << 16
        z.writestr(link, b"../../../../etc/passwd")


def build_03_duplicate_name():
    """Two entries sharing the identical enclosed name. `zipfile` itself
    allows this (it does not deduplicate on write); only the first
    occurrence, by index, may be admitted."""
    path = os.path.join(OUT, "03-duplicate-name.zip")
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("dup.txt", b"first occurrence")
        z.writestr("dup.txt", b"second occurrence, must be refused")


def build_04_high_ratio_bomb():
    """One entry whose real DEFLATE ratio comfortably exceeds
    `MAX_COMPRESSION_RATIO` (200:1) — 8 MiB of one repeated byte, which
    DEFLATE compresses to well under 40 KiB (a genuine >200:1 ratio, not a
    forged header)."""
    path = os.path.join(OUT, "04-high-ratio-bomb.zip")
    payload = b"Q" * (8 * 1024 * 1024)
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("bomb.bin", payload)


def build_05_nested_inner():
    """The archive that becomes `06-nested-outer.zip`'s one entry."""
    inner_path = os.path.join(OUT, "05-nested-inner.zip")
    with zipfile.ZipFile(inner_path, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("leaf.md", b"# leaf\n\ninner content\n")
    return inner_path


def build_06_nested_outer(inner_path):
    """One entry that is itself a well-formed ZIP — depth 1, within
    `MAX_NESTING_DEPTH` (2), so it must recurse."""
    path = os.path.join(OUT, "06-nested-outer.zip")
    with open(inner_path, "rb") as f:
        inner_bytes = f.read()
    with zipfile.ZipFile(path, "w", zipfile.ZIP_STORED) as z:
        z.writestr("inner.zip", inner_bytes)


if __name__ == "__main__":
    build_01_plain_and_directory()
    build_02_symlink()
    build_03_duplicate_name()
    build_04_high_ratio_bomb()
    inner = build_05_nested_inner()
    build_06_nested_outer(inner)
    for name in sorted(os.listdir(OUT)):
        full = os.path.join(OUT, name)
        print(name, os.path.getsize(full), "bytes")
